FROM python:3.13

WORKDIR /code

ENV TMPDIR=/tmp

RUN chmod -R 777 /tmp

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./doc /doc

COPY ./rag-be /code

WORKDIR /code

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]